#message(${IMAGEWIDGET_DIR})
include_directories( ${IMAGETOOLQML_DIR}/widgetsproxy/include)
LINK_DIRECTORIES( ${IMAGETOOLQML_DIR}/widgetsproxy/lib)


IF(CMAKE_BUILD_TYPE STREQUAL Debug)
    set(IMAGETOOL_LIBS IMAGETOOLd)
ELSE()
    set(IMAGETOOL_LIBS IMAGETOOL)
ENDIF()


#SET(IMAGEWIDGET_INCLUDE_DIR ${CMAKE_SOURCE_DIR} CACHE PATH "IMAGEWIDGET_INCLUDE_DIR")
#SET(IMAGEWIDGET_LIBS_DIR "INPUT" CACHE PATH "IMAGEWIDGET_INCLUDE_DIR")
#SET(IMAGEWIDGET_INCLUDE_DIR ${CMAKE_SOURCE_DIR} CACHE PATH "IMAGEWIDGET_INCLUDE_DIR")
#SET(IMAGEWIDGET_LIBS_DIR "INPUT" CACHE PATH "IMAGEWIDGET_INCLUDE_DIR")