#message(${IMAGEWIDGET_DIR})
include_directories( ${IMAGETOOLQML_DIR}/include)
LINK_DIRECTORIES( ${IMAGETOOLQML_DIR}/lib)


IF(CMAKE_BUILD_TYPE STREQUAL Debug)
    set(IMAGETOOLQML_LIBS IMAGETOOLQMLd)
ELSE()
    set(IMAGETOOLQML_LIBS IMAGETOOLQML)
ENDIF()


#SET(IMAGEWIDGET_INCLUDE_DIR ${CMAKE_SOURCE_DIR} CACHE PATH "IMAGEWIDGET_INCLUDE_DIR")
#SET(IMAGEWIDGET_LIBS_DIR "INPUT" CACHE PATH "IMAGEWIDGET_INCLUDE_DIR")